### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by smaragdus** [ramzan/Atmostate#3]
@ramzan 

Hello, do you plan to release [Atmostate](https://github.com/ramzan/Atmostate) on [F-Droid](https://f-droid.org/en/)?

**Comment by ramzan** [comment]
Hi, thanks for your interest. I don't plan on releasing Atmostate on F-Droid since I don't want to publish the API key in the source code. Also, I think there are enough weather apps on F-Droid lol.

**Comment by smaragdus** [comment]
@ramzan 

> Hi, thanks for your interest.

Thanks for the quick response!

> Also, I think there are enough weather apps on F-Droid lol.

Yes, there are. Several days ago I downloaded several of them and picked one after testing them side by side. I haven't already tested yours since I mostly use stuff from [F-Droid](https://f-droid.org/en/). I discovered [Atmostate](https://github.com/ramzan/Atmostate) by chance and I supposed that you might be interested in [F-Droid](https://f-droid.org/en/) release since another of your apps- [Delist](https://github.com/ramzan/Delist), had already been released on [F-Droid](https://f-droid.org/en/packages/ca.ramzan.delist/).

> I don't plan on releasing Atmostate on F-Droid since I don't want to publish the API key in the source code.

I understand, but as far as I know you can get as many API keys as you would need. Also, the users might change the API key with their own one.

Anyway, feel free to close this issue if you don't change your mind.

Regards
